version: '3.8'
        
services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    
    container_name: dash-database-liferay
    image: dash-database-liferay-image
    command: --authentication-policy=mysql_native_password
    restart: always

    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    
    ports:
      - "${MYSQL_PORT}:3306"

  app:
    build: 
      context: ./frontenddash
      dockerfile: Dockerfile
    container_name: app-frontenddash
    image: app-frontenddash-image
    ports:
      - "${LFR_APP_ENV}:5173"

  liferay:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: dash-liferay-portal
    image: dash-liferay-portal-image
    
    depends_on:
      - database
   
    ports:
      - "${LFR_DEBUG_ENV}:8000"
      - "${LFR_PORT_ENV}:8080"